### ISSUE TITLE
Default Theme font different

### ISSUE THREAD

**Issue by fus38xid** [Imgkl/the-dark-side#5]
Hello, i just installed your theme and the font is different compared to the font on the images on the github page.
However this also could be a fault on my end. please lmk if you have a fix for it :)

![Screenshot from 2024-10-09 20-13-56](https://github.com/user-attachments/assets/9de82943-e618-4789-9f32-35fa10d91fe2)

**Comment by Imgkl** [comment]
Hey @fus38xid, 

The font, I used on the screenshot was JetBrains Mono. On Themes, AFAIK, we currently can't bundle fonts. 

Here is the settings json for your reference. Install the JetBrains Mono font and update your settings. It should reflect fine.

```
{
  "assistant": {
    "default_model": {
      "provider": "openai",
      "model": "gpt-4o"
    },
    "version": "2"
  },
  "collaboration_panel": {
    "dock": "right"
  },
  "base_keymap": "VSCode",
  "theme": "The Dark Side",
  "ui_font_size": 15,
  "buffer_font_size": 15,
  "buffer_line_height": "comfortable",
  "auto_update_extensions": {
    "enabled": true
  },
  "telemetry": {
    "enabled": false
  },
  "buffer_font_family": "JetBrains Mono",
  "terminal": {
    "font_family": "JetBrains Mono",
    "line_height": "comfortable",
    "font_size": 15
  },
  "ui_font_family": "JetBrains Mono",
  "format_on_save": "off",
  "cursor_blink": true
}
```

**Comment by Imgkl** [comment]
lmk if this solved your issue. I can close this. Happy to give more info on anything else is needed.
